"""your migration message

Revision ID: 3911f976d572
Revises: 99282eabc808
Create Date: 2025-12-28 18:50:45.244189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3911f976d572'
down_revision: Union[str, None] = '99282eabc808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heritage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_map', sa.String(length=255), nullable=False),
    sa.Column('image_cover', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heritage_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('heritage_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['heritage_id'], ['heritage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('heritage_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['heritage_id'], ['heritage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_rules')
    op.drop_table('heritage_photos')
    op.drop_table('heritage')
    # ### end Alembic commands ###

